import {
  ChartIcon,
  ClipboardIcon,
  IdCardIcon,
  InvoiceIcon,
  MessageIcon,
  RouteIcon,
  SettingsIcon,
  TruckIcon,
  WarehouseIcon,
} from "@/components/ui/icons";

export const employeeModules = [
  {
    key: "disposition",
    href: "/mitarbeiter/disposition",
    label: "Disposition",
    description: "Touren planen, Fahrer & Fahrzeuge zuweisen.",
    icon: RouteIcon,
  },
  {
    key: "lager",
    href: "/mitarbeiter/lager",
    label: "Lagerverwaltung & Inventuren",
    description: "Bestände, Wareneingänge und digitale Inventuren.",
    icon: WarehouseIcon,
  },
  {
    key: "fahrzeuge",
    href: "/mitarbeiter/fahrzeuge",
    label: "Fahrzeugverwaltung",
    description: "Fuhrpark, Wartungen und Prüftermine im Überblick.",
    icon: TruckIcon,
  },
  {
    key: "fahrtenbuch",
    href: "/mitarbeiter/fahrtenbuch",
    label: "Digitales Fahrtenbuch",
    description: "Fahrten erfassen und Kilometerstände dokumentieren.",
    icon: ClipboardIcon,
  },
  {
    key: "fahrerkarte",
    href: "/mitarbeiter/fahrerkarte",
    label: "Digitale Fahrerkarte",
    description: "Lenk- und Ruhezeiten je Fahrer im Blick.",
    icon: IdCardIcon,
  },
  {
    key: "auftraege",
    href: "/mitarbeiter/auftraege",
    label: "Aktuelle Aufträge",
    description: "Eigene Aufträge einsehen und mit der Disposition schreiben.",
    icon: MessageIcon,
  },
  {
    key: "rechnungen",
    href: "/mitarbeiter/rechnungen",
    label: "Rechnungserstellung",
    description: "Rechnungen direkt erstellen, als PDF exportieren und verwalten.",
    icon: InvoiceIcon,
  },
  {
    key: "finanzen",
    href: "/mitarbeiter/finanzen",
    label: "Finanzbuchhaltung",
    description: "Buchungen, offene Posten und Reporting.",
    icon: ChartIcon,
  },
  {
    key: "verwaltung",
    href: "/mitarbeiter/verwaltung",
    label: "Website-Verwaltung",
    description: "Inhalte der öffentlichen Website pflegen (News, Stellen, Team, u. v. m.).",
    icon: SettingsIcon,
  },
] as const;
