import {
  ChartIcon,
  ClipboardIcon,
  ClockIcon,
  FolderIcon,
  IdCardIcon,
  InvoiceIcon,
  MailIcon,
  MessageIcon,
  PhoneIcon,
  RouteIcon,
  SettingsIcon,
  TruckIcon,
  UsersIcon,
  WarehouseIcon,
} from "@/components/ui/icons";

export const employeeModules = [
  {
    key: "disposition",
    href: "/mitarbeiter/disposition",
    label: "Disposition",
    description: "Touren planen, Fahrer & Fahrzeuge zuweisen.",
    icon: RouteIcon,
  },
  {
    key: "lager",
    href: "/mitarbeiter/lager",
    label: "Lagerverwaltung & Inventuren",
    description: "Bestände, Wareneingänge und digitale Inventuren.",
    icon: WarehouseIcon,
  },
  {
    key: "fahrzeuge",
    href: "/mitarbeiter/fahrzeuge",
    label: "Fahrzeugverwaltung",
    description: "Fuhrpark, Wartungen und Prüftermine im Überblick.",
    icon: TruckIcon,
  },
  {
    key: "fahrtenbuch",
    href: "/mitarbeiter/fahrtenbuch",
    label: "Digitales Fahrtenbuch",
    description: "Fahrten erfassen und Kilometerstände dokumentieren.",
    icon: ClipboardIcon,
  },
  {
    key: "fahrerkarte",
    href: "/mitarbeiter/fahrerkarte",
    label: "Digitale Fahrerkarte",
    description: "Lenk- und Ruhezeiten je Fahrer im Blick.",
    icon: IdCardIcon,
  },
  {
    key: "auftraege",
    href: "/mitarbeiter/auftraege",
    label: "Aktuelle Aufträge",
    description: "Eigene Aufträge einsehen und mit der Disposition schreiben.",
    icon: MessageIcon,
  },
  {
    key: "rechnungen",
    href: "/mitarbeiter/rechnungen",
    label: "Rechnungserstellung",
    description: "Rechnungen direkt erstellen, als PDF exportieren und verwalten.",
    icon: InvoiceIcon,
  },
  {
    key: "finanzen",
    href: "/mitarbeiter/finanzen",
    label: "Finanzbuchhaltung",
    description: "Buchungen, offene Posten und Reporting.",
    icon: ChartIcon,
  },
  {
    key: "kundenstammbaum",
    href: "/mitarbeiter/kundenstammbaum",
    label: "Kundenstammbaum",
    description: "Kundendaten zentral pflegen und in Rechnungen einfach auswählen.",
    icon: UsersIcon,
  },
  {
    key: "stempeluhr",
    href: "/mitarbeiter/stempeluhr",
    label: "Stempeluhr",
    description: "Ein- und ausstempeln und Arbeitszeiten je Woche und Monat im Blick.",
    icon: ClockIcon,
  },
  {
    key: "personalakten",
    href: "/mitarbeiter/personalakten",
    label: "Personalakten",
    description: "Persönliche Daten und Dokumente der Mitarbeiter verwalten.",
    icon: FolderIcon,
  },
  {
    key: "bewerbungen",
    href: "/mitarbeiter/bewerbungen",
    label: "Bewerbungen",
    description: "Eingehende Bewerbungen sichten und den Status je Bewerbung ändern.",
    icon: MailIcon,
  },
  {
    key: "anfragen",
    href: "/mitarbeiter/anfragen",
    label: "Anfragen",
    description: "Kontaktanfragen von der Website sichten und per Discord beantworten.",
    icon: PhoneIcon,
  },
  {
    key: "verwaltung",
    href: "/mitarbeiter/verwaltung",
    label: "Verwaltung",
    description: "Inhalte der öffentlichen Website pflegen (News, Stellen, Team, u. v. m.).",
    icon: SettingsIcon,
  },
] as const;
